# Generated by Django 5.2.8 on 2025-11-13 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('received_date', models.DateTimeField()),
                ('body_text', models.TextField()),
                ('snippet', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('is_phishing', models.BooleanField(default=False)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='SAFE', max_length=20)),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='AIDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('confidence_level', models.CharField(max_length=50)),
                ('perplexity_score', models.FloatField(default=0.0)),
                ('burstiness_score', models.FloatField(default=0.0)),
                ('pattern_score', models.FloatField(default=0.0)),
                ('uniformity_score', models.FloatField(default=0.0)),
                ('indicators', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_detection', to='detector.emailmessage')),
            ],
            options={
                'verbose_name': 'AI Detection Result',
                'verbose_name_plural': 'AI Detection Results',
            },
        ),
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token_file', models.TextField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gmail Account',
                'verbose_name_plural': 'Gmail Accounts',
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='detector.gmailaccount'),
        ),
        migrations.CreateModel(
            name='LinkAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('indicators', models.JSONField(default=list)),
                ('details', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='detector.emailmessage')),
            ],
            options={
                'verbose_name': 'Link Analysis',
                'verbose_name_plural': 'Link Analyses',
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_emails', models.IntegerField(default=0)),
                ('safe_emails', models.IntegerField(default=0)),
                ('phishing_emails', models.IntegerField(default=0)),
                ('ai_generated_emails', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('gmail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='detector.gmailaccount')),
            ],
            options={
                'verbose_name': 'Scan History',
                'verbose_name_plural': 'Scan Histories',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_emails_scanned', models.IntegerField(default=0)),
                ('safe_count', models.IntegerField(default=0)),
                ('phishing_count', models.IntegerField(default=0)),
                ('ai_phishing_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gmail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.gmailaccount')),
            ],
            options={
                'verbose_name': 'Threat Statistics',
                'verbose_name_plural': 'Threat Statistics',
                'ordering': ['-date'],
                'unique_together': {('gmail_account', 'date')},
            },
        ),
    ]
